name: CI-Gradle

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '{{cookiecutter.javaVersion}}' 

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Run tests
      run: ./gradlew test --no-daemon

    - name: Run OWASP Dependency Check
      run: |
        wget -q "https://github.com/jeremylong/DependencyCheck/releases/download/v8.2.1/dependency-check-8.2.1-release.zip"
        unzip -q dependency-check-6.4.2-release.zip
        ./dependency-check/bin/dependency-check.sh --scan . --format "HTML" --out "dependency-check-report"
    
    - name: Generate Javadoc
      run: ./gradlew javadoc --no-daemon

    - name: Archive Javadoc
      uses: actions/upload-artifact@v2
      with:
        name: javadoc
        path: build/docs/javadoc